export const KBLI_2025_CATEGORIES: Record<string, string> = {
  'A': 'PERTANIAN, KEHUTANAN, DAN PERIKANAN',
  'B': 'PERTAMBANGAN DAN PENGGALIAN',
  'C': 'INDUSTRI',
  'D': 'PENYEDIAAN LISTRIK, GAS, UAP/AIR PANAS, DAN UDARA DINGIN',
  'E': 'PENYEDIAAN AIR; PENGELOLAAN AIR LIMBAH, PENANGANAN LIMBAH, DAN REMEDIASI',
  'F': 'KONSTRUKSI',
  'G': 'PERDAGANGAN BESAR DAN ECERAN',
  'H': 'TRANSPORTASI DAN PENYIMPANAN',
  'I': 'AKTIVITAS PENYEDIAAN AKOMODASI DAN MAKAN MINUM',
  'J': 'AKTIVITAS PENERBITAN, PENYIARAN, SERTA PRODUKSI DAN DISTRIBUSI KONTEN',
  'K': 'AKTIVITAS TELEKOMUNIKASI, PEMROGRAMAN KOMPUTER, KONSULTANSI, INFRASTRUKTUR KOMPUTASI, DAN JASA INFORMASI LAINNYA',
  'L': 'AKTIVITAS KEUANGAN DAN ASURANSI',
  'M': 'AKTIVITAS REAL ESTAT',
  'N': 'AKTIVITAS PROFESIONAL, ILMIAH, DAN TEKNIS',
  'O': 'AKTIVITAS ADMINISTRATIF DAN PENUNJANG USAHA',
  'P': 'ADMINISTRASI PEMERINTAHAN DAN PERTAHANAN, SERTA JAMINAN SOSIAL WAJIB',
  'Q': 'PENDIDIKAN',
  'R': 'AKTIVITAS KESEHATAN MANUSIA DAN AKTIVITAS SOSIAL',
  'S': 'KESENIAN, OLAHRAGA, DAN REKREASI',
  'T': 'AKTIVITAS JASA LAINNYA',
  'U': 'AKTIVITAS RUMAH TANGGA SEBAGAI PEMBERI KERJA DAN AKTIVITAS PRODUKSI',
  'V': 'AKTIVITAS BADAN INTERNASIONAL DAN BADAN EKSTRA INTERNASIONAL LAINNYA'
};

export function formatKbliCategory(letter?: string, name?: string): string {
  if (!letter) return (name || "").toUpperCase();
  const officialName = KBLI_2025_CATEGORIES[letter.toUpperCase()];
  if (officialName) {
    return `${letter.toUpperCase()} - ${officialName}`;
  }
  return `${letter.toUpperCase()} - ${(name || "").toUpperCase()}`;
}
