import { Address, ResolutionFlags, Shareholder, CompanyData } from '../../types';

export const INITIAL_ADDRESS: Address = {
  province: '',
  city: '',
  fullAddress: '',
  rt: '',
  rw: '',
  kelurahan: '',
  kecamatan: ''
};

export const INITIAL_RESOLUTIONS: ResolutionFlags = {
  domicile: false,
  address: false,
  capitalBase: false,
  capitalPaid: false,
  capitalBaseDecrease: false,
  capitalPaidDecrease: false,
  reappointment: false,
  kbli: false, 
  management: false,
  shareholders: false,
  companyNameChange: false
};

export const PPAT_TRANSACTION_TYPES = [
  'Akta Jual Beli (AJB)',
  'Akta Hibah',
  'Akta Pembagian Hak Bersama (APHB)',
  'Akta Pemberian Hak Tanggungan (APHT)',
  'Surat Kuasa Membebankan Hak Tanggungan (SKMHT)',
  'Akta Tukar Menukar',
  'Akta Pemasukan ke Dalam Perusahaan (Inbreng)',
  'Akta Pemberian Hak Pakai / Hak Guna Bangunan',
  'Pengecekan Sertipikat BPN',
  'Balik Nama Sertipikat',
  'Roya Hak Tanggungan'
];

export const INITIAL_MANUAL_REP: Shareholder = {
  id: 'manual-rep',
  salutation: 'Tuan',
  name: '',
  birthCity: '',
  birthDate: '',
  nationality: 'WNI',
  nationalityType: 'WNI',
  occupation: '',
  address: { ...INITIAL_ADDRESS },
  nik: '',
  sharesOwned: 0
};

export const INITIAL_STATE: CompanyData = {
  documentType: 'CIRCULAR',
  companyName: '',
  companyShortName: '',
  targetCompanyName: '',
  targetCompanyShortName: '',
  companyType: 'SWASTA NASIONAL',
  npwp: '',
  duration: 'TIDAK TERBATAS',
  status: 'tertutup',
  oldDomicile: '',
  domicile: '',
  domicileStyle: 'KOTA',
  oldAddress: { ...INITIAL_ADDRESS },
  newAddress: { ...INITIAL_ADDRESS },
  oldFullAddress: '',
  fullAddress: '',
  kbliItems: [],
  managementChangeType: 'ALL_DISMISSED',
  oldManagementItems: [],
  newManagementItems: [],
  managementEffectiveUntil: '',
  managementEffectiveUntilType: 'AD',
  managementEffectiveDate: '',
  reappointmentOldExpiredDate: '',
  reappointmentStartDate: '',
  reappointmentEndDate: '',
  originalTotalShares: 0,
  originalAuthorizedShares: 0,
  originalSharePrice: 0,
  originalCapitalBase: 0,
  originalCapitalPaid: 0,
  targetCapitalBase: 0,
  targetCapitalPaid: 0,
  capitalArticleNumber: '4',
  domicileArticleNumber: '1',
  representativeType: 'EXISTING',
  authorizedRepresentativeId: '',
  manualRepresentative: { ...INITIAL_MANUAL_REP },
  signingPlace: '',
  signingDate: '',
  aktaStartTime: '10:00',
  meetingStartTime: '',
  meetingEndTime: '',
  meetingChair: '',
  meetingChairPosition: '',
  invitationNumber: '',
  invitationDate: '',
  meetingAgenda: '',
  establishmentDeedNumber: '',
  establishmentDeedDate: '',
  establishmentNotary: '',
  establishmentNotaryDomicile: '',
  establishmentSkNumber: '',
  establishmentSkDate: '',
  latestAmendmentDeedNumber: '',
  latestAmendmentDeedDate: '',
  latestAmendmentNotary: '',
  latestAmendmentSkNumber: '',
  latestAmendmentSkDate: '',
  amendmentDeeds: [],
  shareholders: [],
  shareTransfers: [],
  finalShareholders: [],
  guests: [],
  managementDismissals: [],
  shareTransfersNew: [],
  capitalSubscriptionsNew: [],
  resolutions: INITIAL_RESOLUTIONS,
  selectedProfileId: '',
  createDraftAktaRups: true,
  draftAktaRupsNumber: '',
  draftAktaRupsOrderNumber: '',
  draftAktaRupsDate: '',
  draftAktaRupsTime: '',
  notaryName: '',
  notaryTitle: '',
  notaryDomicile: '',
  notaryNumber: '',
  notaryDate: '',
  isReplacementNotary: false,
  beneficialOwnerConsent: false,
  rupstFiscalYear: '',
  rupstNetProfit: undefined,
  rupstDividendAmount: undefined,
  rupstRetainedProfit: undefined,
  rupstFinancialReportNumber: '',
  rupstFinancialReportDate: '',
  rupstFinancialReportSignatoryName: '',
  rupstFinancialReportSignatoryPosition: '',
  rupstStatementNeraca: true,
  rupstStatementLabaRugi: false,
  rupstStatementPerubahanEkuitas: false,
  rupstStatementArusKas: false,
  rupstStatementCatatan: false,
  rupstStatementNamaAnggota: false,
  rupstStatementGaji: false,
  rupstAlasanAuditA: true,
  rupstAlasanAuditB: true,
  rupstAlasanAuditC: true,
  rupstAlasanAuditD: true,
  rupstAlasanAuditE: true,
  rupstAlasanAuditF: true,
  rupstIsAudited: false,
  rupstKapName: '',
  rupstKapLicenseNumber: '',
  rupstKapExpiryDate: '',
  rupstAuditReportNumber: '',
  rupstAuditReportDate: '',
  rupstNotulenNumber: '',
  rupstDividends: [],
  rupstDividendPaymentDate: '05 Juni 2026 dan 10 Juni 2026',
  rupstType: 'sirkuler',
  rupstNonAuditedUseKAP: false,
  rupstQuorumArticle: '10',
  rupstQuorumParagraph: '1',
  rupstMeetingEndTime: '',
  rupstInvitationNumber: '',
  rupstInvitationDate: '',
  slHari: '',
  slTanggalHuruf: '',
  slAlasanAuditA: false,
  slAlasanAuditB: false,
  slAlasanAuditC: true,
  slAlasanAuditD: true,
  slAlasanAuditE: false,
  slAlasanAuditF: false,
  slLaporanNomor: '',
  slLaporanTanggalHuruf: '',
  slTahunBukuAkhirHuruf: '',
  saksi1Nama: 'Nendi Suhendi',
  saksi1Lahir: 'Bandung, pada tanggal limabelas Juli seribu sembilan ratus sembilan puluh satu (15-07-1991)',
  saksi1Alamat: 'Jalan Sukaresmi Nomor 12, Rukun Tetangga 005, Rukun Warga 005, Kecamatan Lembang, Desa Mekarwangi',
  saksi1NIK: '3217011507910016',
  saksi2Nama: 'Siti Nur Azizah',
  saksi2Lahir: 'Bandung, pada tanggal tujuh belas Desember seribu sembilan ratus sembilan puluh sembilan (17-12-1999)',
  saksi2Alamat: 'Kabupaten Bandung, Jalan Lembah Pakar Timur II Kampung Sekebuluh Rukun Tetangga 001, Rukun Warga 004, Desa Ciburial, Kecamatan Cimenyan',
  saksi2NIK: '3204065712990001'
};

export const ALLOWED_EMAILS = [
  'appnotputri@gmail.com',
  'rdyndi@gmail.com',
  'notarisppatputri@gmail.com',
  'pu3stan@gmail.com'
];

export enum ProjectCategory {
  BODY_LEGAL = 'BODY_LEGAL',
  MEETING = 'MEETING',
  AGREEMENT = 'AGREEMENT',
  GENERAL_DEED = 'GENERAL_DEED',
  LEGALIZATION = 'LEGALIZATION',
  PPAT = 'PPAT'
}

export const PROJECT_TYPES: Record<ProjectCategory, string[]> = {
  [ProjectCategory.BODY_LEGAL]: [
    'Pendirian PT',
    'RUPS T',
    'RUPS LB',
    'Pendirian CV',
    'Perubahan CV',
    'Pembubaran CV',
    'Pendirian Firma',
    'Perubahan Firma',
    'Pembubaran Firma',
    'Pendirian Yayasan',
    'Perubahan Yayasan',
    'Pembubaran Yayasan',
    'Rapat Pembina',
    'Rapat Pengurus',
    'Rapat Pengawas',
    'Pendirian Perkumpulan',
    'Perubahan Perkumpulan',
    'Pembubaran Perkumpulan',
    'Rapat Anggota',
    'Rapat Pengurus'
  ],
  [ProjectCategory.MEETING]: ['RUPS T', 'RUPS LB', 'Rapat Yayasan', 'Rapat Perkumpulan'],
  [ProjectCategory.PPAT]: [
    'Akta Jual Beli (AJB)',
    'Akta Tukar Menukar',
    'Akta Hibah',
    'Akta Hibah Wasiat',
    'Akta Waris (Peralihan Hak Karena Waris)',
    'Akta Pemasukan Ke Dalam Perusahaan (Inbreng)',
    'Akta Pemisahan Hak Yang Mengakibatkan Peralihan',
    'Akta Penggabungan Usaha (Merger)',
    'Akta Peleburan Usaha (Konsolidasi)',
    'Akta Pemekaran Usaha (Spin-off)',
    'Akta Hadiah',
    'Akta Penunjukan Pembeli Dalam Lelang',
    'Akta Pelaksanaan Putusan Hakim Berkekuatan Hukum Tetap',
    'Akta Pemberian Hak Baru Atas Tanah (Kelanjutan Pelepasan Hak)',
    'Akta Pemberian Hak Baru Atas Tanah (Di Luar Pelepasan Hak)',
    'Akta Pembagian Hak Bersama (APHB)',
    'Akta Pemberian Hak Tanggungan (APHT)',
    'Akta Surat Kuasa Memasang Hak Tanggungan (SKMHT)',
    'Akta Pemberian HGB / Hak Pakai atas Tanah Hak Milik',
    'Akta Pelepasan Hak Atas Tanah',
    'Akta Kustom',
    'Lainnya'
  ],
  [ProjectCategory.AGREEMENT]: [
    'Perjanjian Sewa Menyewa',
    'Perjanjian Kerja Sama',
    'PPJB',
    'Perjanjian Utang Piutang',
    'Akta Hibah',
    'Pengalihan Merek',
    'Lisensi Merek',
    'Pinjam Pakai',
    'Waralaba',
    'Akta Kustom',
    'Lainnya'
  ],
  [ProjectCategory.GENERAL_DEED]: [
    'Akta Kuasa',
    'Akta Pernyataan',
    'Akta Pengakuan Utang',
    'Akta Kustom',
    'Lainnya'
  ],
  [ProjectCategory.LEGALIZATION]: ['Legalisasi', 'Waarmerking']
};

export const MEETING_SUBJECTS = [
  'Perubahan AD',
  'Perubahan Data',
  'Perubahan Nama',
  'Perubahan Alamat',
  'Perubahan KBLI',
  'Perubahan Modal',
  'Perubahan Pengurus',
  'Perubahan Pemegang Saham',
  'Merger',
  'Akuisisi',
  'Spin Off',
  'Pembubaran',
  'Lainnya'
];

export interface RupsLbAgendaItem {
  id: string;
  label: string;
  shortLabel: string;
  badgeColor?: string;
}

export const RUPS_LB_AGENDAS: RupsLbAgendaItem[] = [
  { id: 'pengurus', label: 'Perubahan Susunan Direksi / Dewan Komisaris', shortLabel: 'Perubahan Pengurus', badgeColor: 'bg-purple-50 text-purple-700 border-purple-200' },
  { id: 'pemegang_saham', label: 'Peralihan Saham / Perubahan Pemegang Saham', shortLabel: 'Peralihan Saham', badgeColor: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'peningkatan_modal_dasar', label: 'Peningkatan Modal Dasar', shortLabel: 'Tambah Modal Dasar', badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'peningkatan_modal_disetor', label: 'Peningkatan Modal Ditempatkan & Disetor', shortLabel: 'Tambah Modal Disetor', badgeColor: 'bg-teal-50 text-teal-700 border-teal-200' },
  { id: 'penurunan_modal', label: 'Penurunan Modal Perseroan', shortLabel: 'Penurunan Modal', badgeColor: 'bg-rose-50 text-rose-700 border-rose-200' },
  { id: 'nama_perseroan', label: 'Perubahan Nama Perseroan', shortLabel: 'Ubah Nama PT', badgeColor: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'kedudukan', label: 'Perubahan Tempat Kedudukan', shortLabel: 'Ubah Kedudukan', badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'alamat', label: 'Perubahan Alamat Lengkap', shortLabel: 'Ubah Alamat', badgeColor: 'bg-cyan-50 text-cyan-700 border-cyan-200' },
  { id: 'kbli', label: 'Perubahan Maksud & Tujuan (KBLI)', shortLabel: 'Ubah KBLI', badgeColor: 'bg-orange-50 text-orange-700 border-orange-200' },
  { id: 'anggaran_dasar', label: 'Perubahan Anggaran Dasar Lainnya', shortLabel: 'Ubah Pasal AD', badgeColor: 'bg-violet-50 text-violet-700 border-violet-200' },
  { id: 'pengangkatan_kembali', label: 'Pengangkatan Kembali Pengurus', shortLabel: 'Angkat Kembali', badgeColor: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'perpanjangan_jangka_waktu', label: 'Perpanjangan Jangka Waktu Perseroan', shortLabel: 'Perpanjang Waktu', badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'pelepasan_aset', label: 'Pelepasan / Penjaminan Aset Perseroan', shortLabel: 'Pelepasan Aset', badgeColor: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'pemberian_kuasa', label: 'Pemberian Kuasa / Penegasan RUPS', shortLabel: 'Pemberian Kuasa', badgeColor: 'bg-slate-50 text-slate-700 border-slate-200' },
  { id: 'lainnya', label: 'Agenda Perubahan Lainnya', shortLabel: 'Lainnya', badgeColor: 'bg-slate-50 text-slate-700 border-slate-200' }
];
