import { Address, ResolutionFlags, Shareholder, CompanyData } from '../../types';

export const INITIAL_ADDRESS: Address = {
  province: '',
  city: '',
  fullAddress: '',
  rt: '',
  rw: '',
  kelurahan: '',
  kecamatan: ''
};

export const INITIAL_RESOLUTIONS: ResolutionFlags = {
  domicile: false,
  address: false,
  capitalBase: false,
  capitalPaid: false,
  capitalBaseDecrease: false,
  capitalPaidDecrease: false,
  reappointment: false,
  kbli: false, 
  management: false,
  shareholders: false,
  companyNameChange: false
};

export const INITIAL_MANUAL_REP: Shareholder = {
  id: 'manual-rep',
  salutation: 'Tuan',
  name: '',
  birthCity: '',
  birthDate: '',
  nationality: 'WNI',
  nationalityType: 'WNI',
  occupation: '',
  address: { ...INITIAL_ADDRESS },
  nik: '',
  sharesOwned: 0
};

export const INITIAL_STATE: CompanyData = {
  documentType: 'CIRCULAR',
  companyName: '',
  companyShortName: '',
  targetCompanyName: '',
  targetCompanyShortName: '',
  companyType: 'SWASTA NASIONAL',
  npwp: '',
  duration: 'TIDAK TERBATAS',
  status: 'tertutup',
  oldDomicile: '',
  domicile: '',
  domicileStyle: 'KOTA',
  oldAddress: { ...INITIAL_ADDRESS },
  newAddress: { ...INITIAL_ADDRESS },
  oldFullAddress: '',
  fullAddress: '',
  kbliItems: [],
  managementChangeType: 'ALL_DISMISSED',
  oldManagementItems: [],
  newManagementItems: [],
  managementEffectiveUntil: '',
  managementEffectiveUntilType: 'AD',
  managementEffectiveDate: '',
  reappointmentOldExpiredDate: '',
  reappointmentStartDate: '',
  reappointmentEndDate: '',
  originalTotalShares: 0,
  originalAuthorizedShares: 0,
  originalSharePrice: 0,
  originalCapitalBase: 0,
  originalCapitalPaid: 0,
  targetCapitalBase: 0,
  targetCapitalPaid: 0,
  capitalArticleNumber: '4',
  domicileArticleNumber: '1',
  representativeType: 'EXISTING',
  authorizedRepresentativeId: '',
  manualRepresentative: { ...INITIAL_MANUAL_REP },
  signingPlace: '',
  signingDate: '',
  aktaStartTime: '10:00',
  meetingStartTime: '',
  meetingEndTime: '',
  meetingChair: '',
  meetingChairPosition: '',
  invitationNumber: '',
  invitationDate: '',
  meetingAgenda: '',
  establishmentDeedNumber: '',
  establishmentDeedDate: '',
  establishmentNotary: '',
  establishmentNotaryDomicile: '',
  establishmentSkNumber: '',
  establishmentSkDate: '',
  latestAmendmentDeedNumber: '',
  latestAmendmentDeedDate: '',
  latestAmendmentNotary: '',
  latestAmendmentSkNumber: '',
  latestAmendmentSkDate: '',
  amendmentDeeds: [],
  shareholders: [],
  shareTransfers: [],
  finalShareholders: [],
  guests: [],
  managementDismissals: [],
  shareTransfersNew: [],
  capitalSubscriptionsNew: [],
  resolutions: INITIAL_RESOLUTIONS,
  selectedProfileId: '',
  createDraftAktaRups: true,
  draftAktaRupsNumber: '',
  draftAktaRupsOrderNumber: '',
  draftAktaRupsDate: '',
  draftAktaRupsTime: '',
  notaryName: '',
  notaryTitle: '',
  notaryDomicile: '',
  notaryNumber: '',
  notaryDate: '',
  isReplacementNotary: false,
  beneficialOwnerConsent: false,
  rupstFiscalYear: '',
  rupstNetProfit: undefined,
  rupstDividendAmount: undefined,
  rupstRetainedProfit: undefined,
  rupstFinancialReportNumber: '',
  rupstFinancialReportDate: '',
  rupstFinancialReportSignatoryName: '',
  rupstFinancialReportSignatoryPosition: '',
  rupstStatementNeraca: true,
  rupstStatementLabaRugi: false,
  rupstStatementPerubahanEkuitas: false,
  rupstStatementArusKas: false,
  rupstStatementCatatan: false,
  rupstStatementNamaAnggota: false,
  rupstStatementGaji: false,
  rupstAlasanAuditA: true,
  rupstAlasanAuditB: true,
  rupstAlasanAuditC: true,
  rupstAlasanAuditD: true,
  rupstAlasanAuditE: true,
  rupstAlasanAuditF: true,
  rupstIsAudited: false,
  rupstKapName: '',
  rupstKapLicenseNumber: '',
  rupstKapExpiryDate: '',
  rupstAuditReportNumber: '',
  rupstAuditReportDate: '',
  rupstNotulenNumber: '',
  rupstDividends: [],
  rupstDividendPaymentDate: '05 Juni 2026 dan 10 Juni 2026',
  rupstType: 'rapat',
  rupstNonAuditedUseKAP: true,
  rupstQuorumArticle: '10',
  rupstQuorumParagraph: '1',
  rupstMeetingEndTime: '',
  rupstInvitationNumber: '',
  rupstInvitationDate: '',
  slHari: '',
  slTanggalHuruf: '',
  slAlasanAuditA: false,
  slAlasanAuditB: false,
  slAlasanAuditC: true,
  slAlasanAuditD: true,
  slAlasanAuditE: false,
  slAlasanAuditF: false,
  slLaporanNomor: '',
  slLaporanTanggalHuruf: '',
  slTahunBukuAkhirHuruf: '',
  saksi1Nama: 'Nendi Suhendi',
  saksi1Lahir: 'Bandung, pada tanggal limabelas Juli seribu sembilan ratus sembilan puluh satu (15-07-1991)',
  saksi1Alamat: 'Jalan Sukaresmi Nomor 12, Rukun Tetangga 005, Rukun Warga 005, Kecamatan Lembang, Desa Mekarwangi',
  saksi1NIK: '3217011507910016',
  saksi2Nama: 'Siti Nur Azizah',
  saksi2Lahir: 'Bandung, pada tanggal tujuh belas Desember seribu sembilan ratus sembilan puluh sembilan (17-12-1999)',
  saksi2Alamat: 'Kabupaten Bandung, Jalan Lembah Pakar Timur II Kampung Sekebuluh Rukun Tetangga 001, Rukun Warga 004, Desa Ciburial, Kecamatan Cimenyan',
  saksi2NIK: '3204065712990001'
};

export const ALLOWED_EMAILS = [
  'appnotputri@gmail.com',
  'rdyndi@gmail.com',
  'notarisppatputri@gmail.com'
];
